=== Politecnico-JIC2/HechosHistoricos/HechoHistorico.dtd
<!ELEMENT HistoricalFacts (HistoricalFact+)>
        <!ATTLIST HistoricalFact description CDATA #REQUIRED>
        <!ELEMENT HistoricalFact (Date,Time,ProminentCharacter)>
        <!ELEMENT Time (EPOCA1 | EPOCA2)>
        <!ELEMENT EPOCA1 (#PCDATA)>
        <!ELEMENT EPOCA2 (#PCDATA)>
        <!ELEMENT ProminentCharacter ANY>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Birthday (#PCDATA)>
        <!ELEMENT Date (#PCDATA | DateFormat)*>
        <!ELEMENT DateFormat (Day,Month,Year)>
        <!ELEMENT Day (#PCDATA)>
        <!ELEMENT Month (#PCDATA)>
        <!ELEMENT Year (#PCDATA)>

=== Politecnico-JIC2/HechosHistoricos/HechosHistoricos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE HistoricalFacts SYSTEM "HechoHistorico.dtd">

<HistoricalFacts>
    <HistoricalFact description="IBM da a conocer el PC. ">
        <Date>
            <DateFormat>
                <Day>01</Day>
                <Month>01</Month>
                <Year>2022</Year>
            </DateFormat>
        </Date>
        <Time>
            <EPOCA1></EPOCA1>
        </Time>
        <ProminentCharacter>
            Test person <Name></Name> y birthday:
            <Birthday></Birthday>
        </ProminentCharacter>
    </HistoricalFact>
    <HistoricalFact description="IBM da a conocer el PC. ">
        <Date>
            01-01-2022
        </Date>
        <Time>
            <EPOCA2></EPOCA2>
        </Time>
        <ProminentCharacter>

        </ProminentCharacter>
    </HistoricalFact>
</HistoricalFacts>
